### ISSUE TITLE
StatusEngineExecutionListener exception when tests are skipped

### ISSUE THREAD

**Issue by antublue** [antublue/test-engine#104]
```
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')
	at org.antublue.test.engine.maven.plugin.listener.StatusEngineExecutionListener.executionSkipped(StatusEngineExecutionListener.java:210)
	at org.antublue.test.engine.maven.plugin.listener.DelegatingEngineExecutionListener.lambda$executionSkipped$1(DelegatingEngineExecutionListener.java:57)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.antublue.test.engine.maven.plugin.listener.DelegatingEngineExecutionListener.executionSkipped(DelegatingEngineExecutionListener.java:55)
	at org.antublue.test.engine.internal.descriptor.TestMethodTestDescriptor.skip(TestMethodTestDescriptor.java:165)
	at org.antublue.test.engine.internal.descriptor.ArgumentTestDescriptor.lambda$skip$2(ArgumentTestDescriptor.java:244)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2351)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1116)
	at org.antublue.test.engine.internal.descriptor.ArgumentTestDescriptor.skip(ArgumentTestDescriptor.java:238)
	at org.antublue.test.engine.internal.descriptor.ArgumentTestDescriptor.execute(ArgumentTestDescriptor.java:118)
	at org.antublue.test.engine.internal.descriptor.ClassTestDescriptor.lambda$execute$1(ClassTestDescriptor.java:215)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2351)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1116)
	at org.antublue.test.engine.internal.descriptor.ClassTestDescriptor.execute(ClassTestDescriptor.java:209)
	at org.antublue.test.engine.internal.descriptor.ClassTestDescriptor.execute(ClassTestDescriptor.java:102)
	at org.antublue.test.engine.internal.util.Executor.lambda$execute$1(Executor.java:125)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by antublue** [comment]
Fixed in 7.0.2 (https://github.com/antublue/test-engine/releases/tag/7.0.2)
