### ISSUE TITLE
Test Engine class loading issues

### ISSUE THREAD

**Issue by antublue** [antublue/test-engine#6]
**Test  Scenario**

Test class that uses classes from `org.testcontainers:testcontainers` and `org.testcontainers:kafka`

**Expected Behavior**

All tests should run successfully

**Actual Behavior**

Classloading issues for dependent classes

```
java.lang.NoClassDefFoundError: org/junit/rules/TestRule
    at java.base/java.lang.ClassLoader.defineClass1(Native Method)
    at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
    at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
    at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:555)
    at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
    at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    at example.testcontainers.KafkaTest.createNetwork(KafkaTest.java:58)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

**Identified Resolution**

The Test Engine Maven Plugin `requiresDependencyResolution` scope is incorrect...

```
@Mojo(name = "test", threadSafe = true, requiresDependencyResolution = ResolutionScope.RUNTIME)
```

... and should be...

```
@Mojo(name = "test", threadSafe = true, requiresDependencyResolution = ResolutionScope.TEST)
```

**Comment by antublue** [comment]
Resolved in v3.0.2
